runnable: true

pipeline:
  - segmentation.Download
  - segmentation.Unzip
  - segmentation.Segmentation
  - segmentation.Output

config:
  download:
    url: https://zenodo.org/record/3362976/files/B2.zip

scopes:
  segmentation: 'seg/%s.png'

input_ids:
  - B2--W00026--P00001--Z00000--T00000--dapi.tif